version: "3.7"

services:
    mysql:
        image: mysql:5.7
        container_name: issatex_mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports: 
            - 3307:3306
        volumes:
            - issatex-mysql-data:/var/lib/mysql
        networks: 
            - symfony

    php:
        container_name: 'issatex_app'
        build:
          context: ./php
        ports:
          - 9001:8088
        environment: 
            APP_ENV: dev
            DATABASE_URL: mysql://root:secret@mysql:3306/issatex
            MERCURE_URL: http://mercure:8000/.well-known/mercure
            # MERCURE_PUBLIC_URL: http://${SERVER_NAME:-localhost}/.well-known/mercure
            MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET:-!ChangeMe!}
        volumes:
          - ./issatex:/var/www/issatex
        networks: 
            - symfony
        depends_on:
            - mysql
    
    nginx:
        image: nginx:1.21-alpine
        container_name: issatex_nginx
        # environment:
            # MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
            # MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
        ports:
            - 8001:80
        volumes:
            - ./issatex:/var/www/issatex
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks: 
            - symfony
    
    phpmyadmin:
        image: phpmyadmin:5.1.1
        container_name: issatex_phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 8080:80
        depends_on:
            - mysql
        networks: 
            - symfony
    
    mailcatcher:
        image: schickling/mailcatcher
        container_name: issatex_mailcatcher
        ports: [1025, 1080]
        networks: 
            - symfony
    
    mercure:
        image: dunglas/mercure
        container_name: issatex_mercure
        restart: unless-stopped
        environment:
            # Uncomment the following line to disable HTTPS
            SERVER_NAME: ':8000'
            MERCURE_PUBLISHER_JWT_KEY: ${JWT_KEY}
            MERCURE_SUBSCRIBER_JWT_KEY: ${JWT_KEY}
            CORS_ALLOWED_ORIGINS: '*'
            PUBLISH_ALLOWED_ORIGINS: '*'
            ALLOW_ANONYMOUS: 1
        # Uncomment the following line to enable the development mode
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "8000:8000"
            # - "443:443"
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
          - php
        networks: 
            - symfony
    
    # redis:
    #     image: redis:5-alpine
    #     container_name: ${APP_NAME}-redis
    #     ports: [6379]

    # rabbitmq:
    #     image: rabbitmq:3.7-management
    #     container_name: ${APP_NAME}-rabbitmq
    #     ports: [5672, 15672]

volumes:
    issatex-mysql-data:
    caddy_data:
    caddy_config:
networks: 
    symfony: