mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
            # url: https://mercure-hub.example.com/.well-known/mercure
            # jwt:
            #     secret: '!ChangeMe!'
